/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholar;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Bruktawit
 */
public class ApplicationForm extends javax.swing.JFrame {
Connection conn;
Statement sst;

Statement sss;
Statement tss;
 boolean selfsponsered=false;
       boolean scholarship=false;
       PreparedStatement pst;
            PreparedStatement pss;

    /**
     * Creates new form ApplicationForm
     */
    public ApplicationForm() {
        try{
            initComponents();
            try{
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/scholarship","root","");
                if(conn != null){
                JOptionPane.showMessageDialog(null,"connection created");
                }
                
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"connection not created");
                System.out.println(e.getMessage());
            }
            PreparedStatement psss;
            psss=conn.prepareStatement("select * from employee where Type=?");
            psss.setString(1, "Promoter");
            
            ResultSet rss=psss.executeQuery();
            while(rss.next()){
                System.out.println(rss.getString("EmployeeId"));
                promoID.addItem(rss.getString("EmployeeId"));
            }
            
            selfLabel.setVisible(false);
            buttonGroup1.add(self);
            buttonGroup1.add(Scholar);
            Prelation.add("Myself");
            Prelation.add("Sibling");
            Prelation.add("Parent");
            Prelation.add("Friend");
            Prelation.add("Spouse");
            Prelation.add("Other kind");
            buttonGroup2.add(SF);
            buttonGroup2.add(SM);
            buttonGroup3.add(PSF);
            buttonGroup3.add(PSM);
            promoID.add("I don't have any");
            unis();
           
        }
        catch(SQLException ex){
            Logger.getLogger(ApplicationForm.class.getName()).log(Level.SEVERE,null, ex);
        }
          }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        field = new javax.swing.JTextField();
        education = new javax.swing.JTextField();
        university = new javax.swing.JTextField();
        scores = new javax.swing.JTextField();
        explanation = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        self = new javax.swing.JRadioButton();
        Scholar = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        selfLabel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Pname = new javax.swing.JTextField();
        Prelation = new java.awt.Choice();
        jLabel12 = new javax.swing.JLabel();
        Pphone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Pcountry = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Pnamel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PSF = new javax.swing.JRadioButton();
        PSM = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        SM = new javax.swing.JRadioButton();
        SF = new javax.swing.JRadioButton();
        promoID = new java.awt.Choice();
        jLabel18 = new javax.swing.JLabel();
        Univ = new java.awt.Choice();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jTextField1.setText("FILL IN THE FOLLOWING FORM...WE WILL SEND LATEST SCHOLARSHIPS THAT SUIT YOU");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("FIRST NAME:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("LAST NAME:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("E-MAIL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("The field you want to study E.g B.Sc:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Educational Background:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("The University you want to Join:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Standardized exam scores(if any):");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Explanation(if any):");

        submitbutton.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        self.setText("Self_Sponsered");
        self.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selfActionPerformed(evt);
            }
        });

        Scholar.setText("Scholarship");
        Scholar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScholarActionPerformed(evt);
            }
        });

        jLabel9.setText("Payment options");

        jLabel10.setText("Payer Detials");

        jLabel11.setText("FName");

        jLabel12.setText("Relation");

        jLabel13.setText("Phone");

        jLabel14.setText("Country");

        jLabel15.setText("LastName");

        jLabel17.setText("SEX");

        PSF.setText("FEMALE");

        PSM.setText("MALE");

        javax.swing.GroupLayout selfLabelLayout = new javax.swing.GroupLayout(selfLabel);
        selfLabel.setLayout(selfLabelLayout);
        selfLabelLayout.setHorizontalGroup(
            selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selfLabelLayout.createSequentialGroup()
                .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(selfLabelLayout.createSequentialGroup()
                        .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(selfLabelLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(selfLabelLayout.createSequentialGroup()
                                .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)))
                                .addGap(31, 31, 31)))
                        .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Pphone)
                                .addComponent(Prelation, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addComponent(Pcountry))
                            .addGroup(selfLabelLayout.createSequentialGroup()
                                .addComponent(PSF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PSM)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(selfLabelLayout.createSequentialGroup()
                .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(selfLabelLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pnamel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(selfLabelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        selfLabelLayout.setVerticalGroup(
            selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selfLabelLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pnamel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selfLabelLayout.createSequentialGroup()
                        .addComponent(Prelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Pcountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(selfLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(PSF)
                    .addComponent(PSM))
                .addContainerGap())
        );

        jLabel16.setText("Sex");

        SM.setText("MALE");

        SF.setText("FEMALE");

        jLabel18.setText("PROMOTER ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(education, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(explanation)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(self)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Scholar)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Univ, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scores, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitbutton)
                                .addGap(130, 130, 130))
                            .addComponent(university, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lastname))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(promoID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SM)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SF)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(promoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SM)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel16)
                        .addGap(4, 4, 4)
                        .addComponent(SF)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Univ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scores, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(education)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(explanation, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(self)
                    .addComponent(Scholar)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(university, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void unis(){
    try {
        tss=conn.createStatement();
        ResultSet rssp=tss.executeQuery("select * from university");
        while(rssp.next()){
        Univ.add(rssp.getString("UniversityName"));
        }
    } catch (SQLException ex) {
        Logger.getLogger(ApplicationForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    
    
    
    
    }
    
    
    
    
    
    
    
    
    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        try{
            boolean valid=true;
            sst=conn.createStatement();
           
            //String query="insert into applicationform values('"firstname.getText()+"','"+lastname.getText()+"')";
            //String name=firstname.getText();
            //String lname=lastname.getText();
            String qs="insert into dependent values(?,?,?,?,?,?,?)";
            String q="insert into applicationform (Student,StudentLastName,Field,Education,University,Scores,Explanation,Email,Payment,Sex,PromoterID)values(?,?,?,?,?,?,?,?,?,?,?)";
            String queryyy="insert into applicationform (Student,StudentLastName,Field,Education,University,Scores,Explanation,Email)values('"+firstname.getText()+"','"+lastname.getText()+"','"+field.getText()+"','"+education.getText()+"','"+university.getText()+"','"+scores.getText()+"','"+explanation.getText()+"','"+email.getText()+"')";
            //String queryy="insert into applicationforn(StudentName,StudentLastName)values('"+firstname.getText()+"','"+lastname.getText()+"')";
            ArrayList<Character> symbols;
            symbols = new ArrayList<>();
            String payment=null;
            int numb=0;;
            char[] chars={'1','2','3','4','5','6','7','8','9','-','_','+','~',' ','!','@','#','$','%','^','&','*','(',')','-','_','[',']','{','}','<','>','?','.',',',':',';'};
            for(char x:chars){
            symbols.add(x);
            }
            pst=conn.prepareStatement(q);
            pss=conn.prepareStatement(qs);
            
                for(char s:firstname.getText().toCharArray()){
                    System.out.println(s);
                if(symbols.contains(s)){
                    JOptionPane.showMessageDialog(null, "First Name can only contain Alphabets");
                    valid=false;
                    break;
                }
                }
                 String fn=firstname.getText();
            if(fn.length()<1 ){
                JOptionPane.showMessageDialog(null, "First Name Cannot be null");
                valid=false;
                }
            
            System.out.println("FirstName "+valid);
             for(char s:lastname.getText().toCharArray()){
                    System.out.println(s);
                if(symbols.contains(s)){
                    JOptionPane.showMessageDialog(null, "Last Name can only contain Alphabets");
                    valid=false;
                    break;
                }
                }
             String ln=lastname.getText();
            if(ln.length()<1 ){
                JOptionPane.showMessageDialog(null, "Last Name Cannot be null");
                valid=false;
                }
            System.out.println("LastName "+valid);
            if(!email.getText().contains("@")){
            JOptionPane.showMessageDialog(null,"Please enter a valid email");
            valid=false;
            }
            else if(!email.getText().contains(".com")){
            JOptionPane.showMessageDialog(null,"Please enter a valid email" );
            valid=false;
            }
            System.out.println("Email "+valid);
             String sex="Empty";
        if(SF.isSelected()){
        sex="FEMALE";
        }
        else if(SM.isSelected()){
        sex="MALE";
        }
        System.out.println(sex);
        if("Empty".equals(sex)){
        JOptionPane.showMessageDialog(null, "SEX cannot be a null value");
        valid=false;
        
        }
        System.out.println("Sex "+valid);
        System.out.println("Finished Main "+valid);
            String sexx="Empty";
            
            if(selfsponsered==true && scholarship==false){
                
                
                payment="Self spnosered";
            for(char s:Pname.getText().toCharArray()){
                    System.out.println(s);
                if(symbols.contains(s)){
                    JOptionPane.showMessageDialog(null, "First Name can only contain Alphabets");
                    valid=false;
                    break;
                }
                String pn=Pname.getText();
            if(fn.length()<1 ){
                JOptionPane.showMessageDialog(null, "First Name Cannot be null");
                
                valid=false;
                }
            }
                System.out.println("FirstName Done"+valid);
             for(char s:Pnamel.getText().toCharArray()){
                    System.out.println(s);
                if(symbols.contains(s)){
                    JOptionPane.showMessageDialog(null, "Last Name can only contain Alphabets");
                    valid=false;
                    break;
                }
                String pnl=Pnamel.getText();
            if(pnl.length()<1 ){
                JOptionPane.showMessageDialog(null, "First Name Cannot be null");
                
                valid=false;
                }
            }
             System.out.println("LastName Done"+valid);
            if(Prelation.getSelectedItem().isEmpty()){
            JOptionPane.showMessageDialog(null, "Relationship with Payer cannot be null");
            }
            System.out.println("Rship Done"+valid);
            ArrayList<Integer> numbs=new ArrayList<>(); 
            for(int i=0;i<10;i++){
            numbs.add(i);
            }
            if(Pphone.getText().charAt(0)!='+' && Pphone.getText().length()<11){
              valid=false;
            }
           
            System.out.println("Phone Done"+valid);
            for(char s:Pcountry.getText().toCharArray()){
                    System.out.println(s);
                if(symbols.contains(s)){
                    JOptionPane.showMessageDialog(null, "Country Name can only contain Alphabets");
                    valid=false;
                    break;
                }
                String pn=Pcountry.getText();
            if(fn.length()<1 ){
                JOptionPane.showMessageDialog(null, "Country Name Cannot be null");
                
                valid=false;
                }
            }
                System.out.println("Country finished "+valid);
               
        if(PSF.isSelected()){
        sexx="FEMALE";
        }
        else if(PSM.isSelected()){
        sexx="MALE";
        }
        System.out.println(sexx);
        if("Empty".equals(sexx)){
        JOptionPane.showMessageDialog(null, "SEX cannot be a null value");
        valid=false;
            
        }
                System.out.println("Sex finsished "+sexx);
        System.out.println("Finished self sponserd "+valid);
            }
            else{
            payment="Scholarship";
            }
            
            
       
               if(valid){
                   System.out.println("About to update");
            pst.setString(1,firstname.getText());
            pst.setString(2,lastname.getText());
            pst.setString(3,field.getText());
            pst.setString(4,education.getText());
            pst.setString(5,Univ.getSelectedItem());
            pst.setString(6,scores.getText());
            pst.setString(7,explanation.getText());
            pst.setString(8,email.getText());
            pst.setString(9, payment);
            pst.setString(10, sex);
            pst.setString(11, promoID.getSelectedItem());
            System.out.println("Almost updated");
            pst.executeUpdate();
            //sst.executeUpdate(queryyy);
            JOptionPane.showMessageDialog(null,"Successfully Submitted!Check your Email soon");
            //JOptionPane.showMessageDialog(null,"Button Pressed");*/
            sst=conn.createStatement();
               }
               if(selfsponsered==true && scholarship==false && valid){
                   System.out.println("Self sponsered");
                   pss.setString(1, Pname.getText());
                   pss.setString(2, Pnamel.getText());
                   pss.setString(3, Prelation.getSelectedItem());
                   pss.setString(4, Pphone.getText());    
                  
                   pss.setString(5, sexx);
                   pss.setString(6, email.getText());
                   pss.setString(7, Pcountry.getText());
                   pss.executeUpdate();
                   System.out.println("Updated Dependent");
               }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"You have an Error on your form");
            e.printStackTrace();
       
        }
        
        
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void selfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selfActionPerformed
            selfLabel.setVisible(true);
            selfsponsered=true;
            System.out.println("selfsponsered true");
            System.out.println("scholarship false");
            scholarship=false;
        // TODO add your handling code here:
    }//GEN-LAST:event_selfActionPerformed

    private void ScholarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScholarActionPerformed
        // TODO add your handling code here:
         selfLabel.setVisible(false);
         selfsponsered=false;
         System.out.println("selfsponsered false");
         scholarship=true;
         System.out.println("scholarship true");
    }//GEN-LAST:event_ScholarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ApplicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton PSF;
    private javax.swing.JRadioButton PSM;
    private javax.swing.JTextField Pcountry;
    private javax.swing.JTextField Pname;
    private javax.swing.JTextField Pnamel;
    private javax.swing.JTextField Pphone;
    private java.awt.Choice Prelation;
    private javax.swing.JRadioButton SF;
    private javax.swing.JRadioButton SM;
    private javax.swing.JRadioButton Scholar;
    private java.awt.Choice Univ;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField education;
    private javax.swing.JTextField email;
    private javax.swing.JTextField explanation;
    private javax.swing.JTextField field;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lastname;
    private java.awt.Choice promoID;
    private javax.swing.JTextField scores;
    private javax.swing.JRadioButton self;
    private javax.swing.JPanel selfLabel;
    private javax.swing.JButton submitbutton;
    private javax.swing.JTextField university;
    // End of variables declaration//GEN-END:variables
}
