/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dagi
 */


public class EmployeeForm extends javax.swing.JFrame {
Connection conni;
Statement ssti;
PreparedStatement pst;
String eag="null";

    /**
     * Creates new form EmployeeForm
     */
    public EmployeeForm() {
        initComponents();
        buttonGroup1.add(RF);
        buttonGroup1.add(RM);
        buttonGroup2.add(RP);
        buttonGroup2.add(RTG);
        connect();
        //AgentName.setVisible(false);
        jLabel7.setVisible(false);
        //EID.
    }
    /*
    void setFalse(){
        if(AgtBtn.isSelected()){
            System.out.println("pressed");
        tf=true;
        }
        System.out.println("Method called"+tf);
    AgentName.setVisible(tf);
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        EN = new javax.swing.JTextField();
        EID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EL = new javax.swing.JTextField();
        ES = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RF = new javax.swing.JRadioButton();
        RM = new javax.swing.JRadioButton();
        EAGENT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DoneBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        AgtBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        RTG = new javax.swing.JRadioButton();
        RP = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("FIRST NAME:");

        EN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENActionPerformed(evt);
            }
        });

        EID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("LAST NAME:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("EMPLOYEE ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("SEX");

        EL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELActionPerformed(evt);
            }
        });

        ES.setToolTipText("");
        ES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("SALARY");

        RF.setText("FEMALE");

        RM.setText("MALE");

        EAGENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EAGENTActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("AGENT ID");

        DoneBtn.setText("DONE");
        DoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneBtnActionPerformed(evt);
            }
        });

        ClearBtn.setText("CLEAR");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        AgtBtn.setText("Dispaly Agent Name");
        AgtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgtBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("JOBTYPE");

        RTG.setText("TOUR GUIDE");

        RP.setText("PROMOTER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClearBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoneBtn)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AgtBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EAGENT, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RF)
                        .addGap(18, 18, 18)
                        .addComponent(RM))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ES, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RTG)
                                .addGap(18, 18, 18)
                                .addComponent(RP))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EN, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EID, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EL, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RTG)
                    .addComponent(RP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RF)
                    .addComponent(RM))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EAGENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgtBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearBtn)
                    .addComponent(DoneBtn))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void connect(){
             try{
           conni=DriverManager.getConnection("jdbc:mysql://localhost:3306/scholarship","root","");
           if(conni != null){
               System.out.println("connection created!");
           }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"error occured, can't connect.");
        }
             
    }
    
    
    
    private void EAGENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EAGENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EAGENTActionPerformed

    private void DoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneBtnActionPerformed
    try {
        ArrayList<Character> symbols;
            symbols = new ArrayList<>();
            String payment=null;
            int numb=0;;
            char[] chars={'1','2','3','4','5','6','7','8','9','-','_','+','~',' ','!','@','#','$','%','^','&','*','(',')','-','_','[',']','{','}','<','>','?','.',',',':',';'};
            for(char x:chars){
            symbols.add(x);
            }
        boolean valid=true;
        String job="null";
        int salint=0;
        String q="insert into employee values(?,?,?,?,?,?,?)";
         String eid=EID.getText();
          
        if(eid.length()!=6 ){
            JOptionPane.showMessageDialog(null, "Employee ID must be a six or above letter string or number");
            valid=false;
        }
        else if(eid.charAt(0)!='e'){
        JOptionPane.showMessageDialog(null, "Employee ID must start with ");
        valid=false;
        }
        else{
        ResultSet rs=ssti.executeQuery("select EmployeeId from employee");
        while(rs.next()){
        if(eid.equals(rs.getString("EmployeeId"))){
        JOptionPane.showMessageDialog(null, "There is an Employee already registered by the ID "+eid);
        valid=false;
        }
        }
        }
         String en=EN.getText();
         for(char s:EN.getText().toCharArray()){
                    System.out.println(s);
                if(symbols.contains(s)){
                    JOptionPane.showMessageDialog(null, "First Name can only contain Alphabets");
                    valid=false;
                    break;
                }
                }
        if(en.length()<1){
            JOptionPane.showMessageDialog(null, "Employee Name cannot be NUll");
            valid=false;
        }
        for(char s:EL.getText().toCharArray()){
                    System.out.println(s);
                if(symbols.contains(s)){
                    JOptionPane.showMessageDialog(null, "Last Name can only contain Alphabets");
                    valid=false;
                    break;
                }
                }
         String el=EL.getText();
        if(el.length()<1){
            JOptionPane.showMessageDialog(null, "Employee L-Name cannot be NUll");
            valid=false;
        }
        
        String sal=ES.getText();
        try{
        salint=Integer.parseInt(sal);
        }
        catch(Exception z){
        JOptionPane.showMessageDialog(null, "Entered Salary not Accepted; Check if you have Entered only Integers");
        valid=false;
        }
        String sex="Empty";
        if(RF.isSelected()){
        sex="FEMALE";
        }
        else if(RM.isSelected()){
        sex="MALE";
        }
        System.out.println(sex);
        if("Empty".equals(sex)){
        JOptionPane.showMessageDialog(null, "SEX cannot be a null value");
        valid=false;
        }
        if(RTG.isSelected()){
        job="Tour Guide";
        }
        else if(RP.isSelected()){
        job="Promoter";
        }
        else if("null".equals(job)){
        JOptionPane.showMessageDialog(null, "You must Select a jobType");
        valid=false;
        }
       if("null".equals(eag)){
       JOptionPane.showMessageDialog(null, "Agent ID cannot be a null value");
       valid=false;
       }
        
        
        pst=conni.prepareStatement(q);
        pst.setString(1, eid);
        pst.setString(2, en);
        pst.setString(3, el);
        pst.setInt(4, salint);
        pst.setString(5, job);
        pst.setString(6, sex);
        pst.setString(7, eag);
        try{
            if(valid){
        pst.executeUpdate();}
            else{
            JOptionPane.showMessageDialog(null,"The Employee is not successfully registered"+eid+" "+en+" "+el+" "+salint+" "+job+" "+sex+" "+eag);
            }
        }
        catch(Exception x){
            valid=false;
            System.out.println(valid);
            JOptionPane.showMessageDialog(null,"The Employee is not successfully registered"+eid+" "+en+" "+el+" "+salint+" "+job+" "+sex+" "+eag);
        }
        if(valid){
            JOptionPane
        .showMessageDialog(null,"You successfully registered "+en+" "+el);
        }
        // TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_DoneBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void ESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ESActionPerformed

    private void ELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ELActionPerformed

    private void ENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ENActionPerformed

    private void EIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIDActionPerformed
        //System.out.println("asf");
       



        // TODO add your handling code here:
    }//GEN-LAST:event_EIDActionPerformed

    private void AgtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgtBtnActionPerformed
     //AgentName.setVisible(true);
        System.out.println("True");
        try {
        ssti=conni.createStatement();
       
        ResultSet rs=ssti.executeQuery("select * from agent");
        
        eag=EAGENT.getText();
        System.out.println("Enterd"+eag);
        boolean ag=false;
        String agid=null;
        while(rs.next()){
            System.out.println("not found");
            agid=rs.getString("AgentId");
            System.out.println(agid);
            
            
            if(eag.equals(agid)){
                System.out.println("Matched");
                ag=true;
                jLabel7.setVisible(true);
                jLabel7.setText(rs.getString("AgentName")+" "+rs.getString("AgentLastName"));
            }
            else{
                System.out.println("not found");
            }
        }

        // TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_AgtBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgtBtn;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton DoneBtn;
    private javax.swing.JTextField EAGENT;
    private javax.swing.JTextField EID;
    private javax.swing.JTextField EL;
    private javax.swing.JTextField EN;
    private javax.swing.JTextField ES;
    private javax.swing.JRadioButton RF;
    private javax.swing.JRadioButton RM;
    private javax.swing.JRadioButton RP;
    private javax.swing.JRadioButton RTG;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
